from typing import Optional, List
from core.extractor import BaseExtractor
from core.models import VideoInfo
from urllib.parse import urlparse
from utils.logger import Logger

class YtDlpDefaultExtractor(BaseExtractor):
    """
    Default extractor for sites natively supported by yt-dlp (e.g., YouTube).
    Returns a dummy VideoInfo (using page_url instead of m3u8), 
    delegating the extraction responsibility entirely to yt-dlp.
    """
    
    def extract(self, url: str) -> Optional[List[VideoInfo]]:
        Logger.info(f"Using universal extractor (yt-dlp default) for: {url}")
        
        parsed = urlparse(url)
        base_url = f"{parsed.scheme}://{parsed.netloc}/"
        
        # Since yt-dlp will handle the parsing, we use the original URL as the target 
        # and skip HTML parsing. The filename will be generated by yt-dlp (%(title)s).
        return [VideoInfo(
            title="%(title)s",  # Will be resolved by yt-dlp
            m3u8_url=url,       # Not an m3u8, but yt-dlp will process it
            page_url=url,
            referer=base_url,
            origin=base_url
        )]
